services:
  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow-gtfs
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - TRIP_UPD_URL=${TRIP_UPD_URL}
      - VEH_POS_URL=${VEH_POS_URL}
    command: >
      bash -c "
        pip install requests python-dotenv gtfs-realtime-bindings &&
        airflow db init &&
        airflow users create --username admin --password admin \
          --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
        airflow webserver & airflow scheduler
      "
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./exports:/opt/airflow/exports